const AlbumsActionTypes = {
  FETCH_ALBUMS_START: "FETCH_ALBUM_START",
  FETCH_ALBUMS_SUCCESS: "FETCH_ALBUM_SUCCESS",
  FETCH_ALBUMS_FAILURE: "FETCH_ALBUM_FAILURE",

  ADD_ALBUM_START: "ADD_ALBUM_START",
  ADD_ALBUM_SUCCESS: "ADD_ALBUM_SUCCESS",
  ADD_ALBUM_FAILURE: "ADD_ALBUM_FAILURE",

  DELETE_ALBUM_START: "DELETE_ALBUM_START",
  DELETE_ALBUM_SUCCESS: "DELETE_ALBUM_SUCCESS",
  DELETE_ALBUM_FAILURE: "DELETE_ALBUM_FAILURE",

  EDIT_ALBUM_START: "EDIT_ALBUM_START",
  EDIT_ALBUM_SUCCESS: "EDIT_ALBUM_SUCCESS",
  EDIT_ALBUM_FAILURE: "EDIT_ALBUM_FAILURE",

  CLEAR_ALBUM_MESSAGES: "CLEAR_ALBUM_MESSAGES",
};

export default AlbumsActionTypes;
