const PhotosActionTypes = {
  FETCH_PHOTOS_START: "FETCH_PHOTOS_START",
  FETCH_PHOTOS_SUCCESS: "FETCH_PHOTOS_SUCCESS",
  FETCH_PHOTOS_FAILURE: "FETCH_PHOTOS_FAILURE",
};

export default PhotosActionTypes;
