const PhotosActionTypes = {
  FETCH_PHOTOS_START: 'FETCH_PHOTO_START',
  FETCH_PHOTOS_SUCCESS: 'FETCH_PHOTO_SUCCESS',
  FETCH_PHOTOS_FAILURE: 'FETCH_PHOTO_FAILURE',

  ADD_PHOTO_START: 'ADD_PHOTO_START',
  ADD_PHOTO_SUCCESS: 'ADD_PHOTO_SUCCESS',
  ADD_PHOTO_FAILURE: 'ADD_PHOTO_FAILURE',

  DELETE_PHOTO_START: 'DELETE_PHOTO_START',
  DELETE_PHOTO_SUCCESS: 'DELETE_PHOTO_SUCCESS',
  DELETE_PHOTO_FAILURE: 'DELETE_PHOTO_FAILURE',

  EDIT_PHOTO_START: 'EDIT_PHOTO_START',
  EDIT_PHOTO_SUCCESS: 'EDIT_PHOTO_SUCCESS',
  EDIT_PHOTO_FAILURE: 'EDIT_PHOTO_FAILURE',

  CLEAR_PHOTO_MESSAGES: 'CLEAR_PHOTO_MESSAGES',
};

export default PhotosActionTypes;
