const TodosActionTypes = {
  FETCH_TODOS_START: "FETCH_TODO_START",
  FETCH_TODOS_SUCCESS: "FETCH_TODO_SUCCESS",
  FETCH_TODOS_FAILURE: "FETCH_TODO_FAILURE",
  ADD_TODO_START: "ADD_TODO_START",
  ADD_TODO_SUCCESS: "ADD_TODO_SUCCESS",
  ADD_TODO_FAILURE: "ADD_TODO_FAILURE",
  DELETE_TODO_START: "DELETE_TODO_START",
  DELETE_TODO_SUCCESS: "DELETE_TODO_SUCCESS",
  DELETE_TODO_FAILURE: "DELETE_TODO_FAILURE",
  EDIT_TODO_START: "EDIT_TODO_START",
  EDIT_TODO_SUCCESS: "EDIT_TODO_SUCCESS",
  EDIT_TODO_FAILURE: "EDIT_TODO_FAILURE",
};

export default TodosActionTypes;
